language: node_js
node_js:
  - "lts"
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-firefoxos-app' ]; then cd .. && eval "mv $currentfolder generator-firefoxos-app" && cd generator-firefoxos-app; fi
