language: node_js
node_js:
  - "lts/*"
script: "npm run-script test-travis"
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-firefoxos-app' ]; then cd .. && eval "mv $currentfolder generator-firefoxos-app" && cd generator-firefoxos-app; fi
after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"